/*
 *  main.c
 *
 *  Main SoC Platform and Tag System Initialization
 */

#include "sl_component_catalog.h"
#include "sl_system_init.h"
#include "sl_power_manager.h"
#include "sl_system_process_action.h"
#include "em_common.h"
#include "em_cmu.h"
#include "em_rmu.h"
#include "em_gpio.h"
#include "app_assert.h"
#include "app_properties.h"
#include "gatt_db.h"
#include "sl_bluetooth.h"
#include "sl_spidrv_instances.h"
#include "sl_iostream_init_instances.h"
#include "sl_iostream_init_usart_instances.h"
#include "sl_sleeptimer.h"
#include "sl_udelay.h"
#include "stdio.h"

/** Keep auto-generated 'git log' information here (generated by pre-build.bat)
 * If 'git_log.h' file is not present in the root folder, add pre build step
 * command '../pre_build.bat' into project C/C++ Build > Settings > Build Steps
 */
#include "git_log.h"

/** Keep tag specific headers here **/
#include "tag_defines.h"
#include "dbg_utils.h"
#include "tag_power_manager.h"
#include "tag_main_machine.h"
#include "ble_api.h"
#include "ble_manager_machine.h"
#include "as393x.h"
#include "wdog.h"
#include "rtcc.h"
#include "boot.h"
#include "cli.h"
#include "nvm.h"
#include "iadc.h"
#include "lf_decoder.h"


//------------------------------------------------------------------------------
// Tag Main Initialization
//------------------------------------------------------------------------------
void tag_init(void)
{
    // Tag 'uptime' conditional initialization
    tum_preinit();

    // Initialize UART (used by dbg_utils and cli)
    dbg_log_init();
    dbg_log_enable(true);
    dbg_print_banner();

    // Print last reset cause
    boot_print_reset_cause();

    // Check if tag is waking up from deep sleep (EM4)
    tag_check_wakeup_from_deep_sleep();

    // Setup Power Manager settings
    tag_power_settings();

    // Initialize AS3933 device driver
    as39_init(sl_spidrv_as39_spi_handle);

    // Keep antenna disabled for now
    as39_antenna_enable(false, false, false);

    // Initialize RTCC (used by Tag Main Machine and LF Decoder)
    rtcc_init();

    // Initialize LF Decoder
    lf_decoder_init();

#if defined(TAG_WDOG_PRESENT)
    watchdog_init();
    DEBUG_LOG(DBG_CAT_SYSTEM, "Initializing WDOG process...");
#endif

    // Initialize Tag Main Machine "Main System Tick"
    switch(boot_get_mode()) {

        case BOOT_DEFAULT:
            DEBUG_LOG(DBG_CAT_SYSTEM, "Boot Select (boot_mode = 0x%.2X) -> Default mode", boot_get_mode());
            tmm_start(TMM_RUNNING);
#if defined(TAG_DEV_MODE_PRESENT)
            dbg_log_enable(true);
            cli_start();
#else
            dbg_log_enable(false);
#endif
            break;

        case BOOT_MANUFACTURING_TEST:
            DEBUG_LOG(DBG_CAT_SYSTEM, "Boot Select (boot_mode = 0x%.2X) -> Manufacturing mode", boot_get_mode());
            tmm_start(TMM_RUNNING);
            dbg_log_enable(true);
            cli_start();
            break;

        default:
            DEBUG_LOG(DBG_CAT_WARNING, "ERROR Boot Select (boot_mode = 0x%.2X) -> Not recognized...\n", boot_get_mode());
            tmm_start(TMM_RUNNING);
            break;
    }

    while (1)
    {
        // BLE API events
        ble_api_fsm_run();
        sl_power_manager_sleep();
    }
}

//------------------------------------------------------------------------------
// Main System Initialization
//------------------------------------------------------------------------------
int main(void)
{
    //*************************************************************************
    // Custom Boot Select
    //*************************************************************************
    boot_init();

    //*************************************************************************
    // Initialize Silicon Labs device, system, service(s) and protocol stack(s).
    //*************************************************************************
    sl_system_init();

    //*************************************************************************
    // BLE Tag System Initialization
    //*************************************************************************
    tag_init();

}




